# Netlify deployment beállítások
[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Redirect minden route-ot az index.html-re (SPA support)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

